export { default as AndroidStudioIcon } from 'assets/svg/AndroidStudio.svg';
export { default as FigmaIcon } from 'assets/svg/Figma-Dark.svg';
export { default as GitIcon } from 'assets/svg/Git.svg';
export { default as GithubIcon } from 'assets/svg/github.svg';
export { default as JetpackIcon } from 'assets/svg/jetpack.svg';
export { default as KotlinIcon } from 'assets/svg/Kotlin_Icon.svg';
export { default as LinkedinIcon } from 'assets/svg/linkedin.svg';
export { default as MenuIcon } from 'assets/svg/menu-hamburguer.svg';
export { default as XIcon } from 'assets/svg/x-close.svg';